###
# data sources
data_sources:
    sname: &sname
      gcp-cases
    path_to_cat_json: '/glade/u/home/eromashkova/codes/nbscuid-examples/basic-demo/gcp-cases.json'
    subset:
      case:
        - 'g.e22.GOMIPECOIAF_JRA-1p4-2018.TL319_g17.GCB_2022.BCRD'
    run_dir: .
    nb_path_root: nbscuid_test_nbs

###
# computation config keys
computation_config:
    default_kernel_name: diag-sandbox
    use_cluster: True
    account: NCGD0011


###
# book table of contents
book_toc:
  format: jb-book
  root: description
  parts:
    - caption: Sea Surface Height
      chapters:
        - file: ssh
    - caption: MOC
      chapters:
        - glob: moc-view*

###
# book _config.yml keys
book_config_keys:
  title: nbscuid demo
  repository:
    url: https://github.com/rmshkv/nbscuid
    path_to_book: notebooks
    branch: main
    

###
# publish location keys
publish_location:
    remote_mach: thorodin.cgd.ucar.edu
    ### this will not generalize, fix!
    remote_dir: /project/webshare/projects/ocean-diagnostics-books/eromashkova/gcp-cases

###
# computational notebooks
compute_notebooks:  

  description:
    use_cluster: False
    parameter_groups:
      none:
        sname: *sname
  
  ssh:
    use_cluster: True
    subset:
      frequency: 'month_1'
      component: 'ocn'
      variable: 'SSH'
    parameter_groups:  
      none:
        sname: *sname

  POP_MOC_extract_cat:
    use_cluster: True
    kernel_name: diag-sandbox-moc-pop-tools
    subset:
      frequency: 'month_1'
      component: 'ocn'
      variable: 'MOC'
    parameter_groups:  
      none:
        sname: *sname
       
  moc-view:
    use_cluster: True
    kernel_name: diag-sandbox-moc-pop-tools
    dependency: 'POP_MOC_extract_cat'
    parameter_groups:
      26n:
        sname: *sname
        title_param: "26n"
        
        
