###
# data sources
data_sources:
    sname: &sname
      placeholder-sname
    run_dir: .
    nb_path_root: nblibrary

###
# computation config keys
computation_config: 
    default_kernel_name: mom6_solutions
    use_cluster: True
    account: NCGD0011


###
# book table of contents
book_toc:
  format: jb-book
  root: intro
  parts:
    - caption: mom6-solutions notebooks
      chapters:
        - file: equatorial
        - file: moc
        - file: ocean_stats
        # - file: pht
        - file: surface
        - file: transports
        - file: ts_biases


###
# book _config.yml keys
book_config_keys:
  title: mom6_solutions automation
  repository:
    url: https://github.com/rmshkv/nbscuid
    path_to_book: notebooks
    branch: main
    

###
# computational notebooks
compute_notebooks:  

  intro:
    use_cluster: False
    parameter_groups:
      none:
        sname: *sname
  
  equatorial:
    use_cluster: True
    parameter_groups:  
      none:
        sname: *sname
        obs_path: '/glade/u/home/gmarques/Notebooks/CESM_MOM6/WOA18_remapping/'
        obs_suffix: '_tx0.66v1_34lev_ann_avg.nc'
  
  moc:
    use_cluster: True
    parameter_groups:  
      none:
        sname: *sname
        
  ocean_stats:
    use_cluster: True
    parameter_groups:  
      none:
        sname: *sname
          
#   pht:
#     use_cluster: False
#     parameter_groups:  
#       none:
#         sname: *sname

  surface:
    use_cluster: True
    parameter_groups:  
      none:
        sname: *sname

  transports:
    use_cluster: True
    parameter_groups:  
      none:
        sname: *sname
        
  ts_biases:
    use_cluster: True
    parameter_groups:  
      none:
        sname: *sname
  
  

        
        
