###
# data sources
data_sources:
    sname: &sname
      placeholder-sname
    run_dir: .
    nb_path_root: nblibrary

###
# computation config keys
computation_config:
    default_kernel_name: nbscuid-dask-debug
    use_cluster: True
    account: NCGD0011


###
# book table of contents
book_toc:
  format: jb-book
  root: dasktest
  parts:
    - caption: dask debugging
      chapters:
        - file: dasktest2


###
# book _config.yml keys
book_config_keys:
  title: dask debugging
  repository:
    url: https://github.com/rmshkv/nbscuid
    path_to_book: notebooks
    branch: main
    

###
# computational notebooks
compute_notebooks:  

  dasktest:
    use_cluster: True
    parameter_groups:
      none:
        sname: *sname
  dasktest2:
    use_cluster: True
    parameter_groups:
      none:
        sname: *sname
  
  

        
        
