
################## SETUP ##################

################
# Data Sources #
################
data_sources:
    # sname is any string used as a nickname for this configuration. It will be
    ### used as the name of the folder your computed notebooks are put in
    sname: &sname
      placeholder-title
    
    # run_dir is the path to the folder you want
    ### all the files associated with this configuration
    ### to be created in
    run_dir: .

    # nb_path_root is the path to the folder that nbscuid will
    ### look for your template notebooks in. It doesn't have to 
    ### be inside run_dir, or be specific to this project, as
    ### long as the notebooks are there
    nb_path_root: nblibrary

######################
# Computation Config #
######################

computation_config: 

    # default_kernel_name is the name of the environment that
    ### the notebooks in this configuration will be run in by default.
    ### It must already be installed on your machine. You can also
    ### specify a different environment than the default for any
    ### notebook in NOTEBOOK CONFIG

    default_kernel_name: nbscuid-tutorial1


############# NOTEBOOK CONFIG #############

############################
# Notebooks and Parameters #
############################

# All parameters under global_params get passed to all the notebooks

global_params:
    test_global_param: hello

compute_notebooks:  

  # This is where all the notebooks you want run and their
  ### parameters are specified. Several examples of different
  ### types of notebooks are provided.

  # The first key (here simple_no_params_nb) is the name of the
  ### notebook from nb_path_root, minus the .ipynb
  simple_no_params_nb:
    parameter_groups:
      none:
        sname: *sname
  
  params_nb:
    parameter_groups: 
      none:
        # This notation pulls in the sname parameter set earlier
        ### in the file, so it can be referenced in the notebook, e.g. if 
        ### you want to use it in a title Markdown cell
        sname: *sname

        # These parameters will be read into the notebook, so for example
        ### a variable will be created with the name param_1 and value
        ### "some_string" in the executed notebook. Note that parameters
        ### can have any name.

        param_1: some_string
        param_2: another_string
  
  another_params_nb:
    #dependency: params_nb
    parameter_groups:  
      none:
        sname: *sname

        # Parameters can be other formats besides strings, like ints,
        ### floats, and dicts

        param_1: {key1: dict_entry1, key2: dict_entry2}
        param_2: 12345

  multiple_param_groups_nb:
    parameter_groups: 
    
      # You can execute a single template notebook with multiple different
      ### parameter sets with the following notation. In the other notebooks
      ### above, the parameter_group "none" indicates that there is only
      ### one parameter group.

      group_1:
        sname: *sname
        nb_number: 3
        param_1: some_string
        param_2: {key1: dict_entry1, key2: dict_entry2}
      group_2:
        sname: *sname
        nb_number: 4
        param_1: some_different_string
        param_2: {key1: dict_entry3, key2: dict_entry4}
        
compute_scripts:

    test_script1:
        # dependency: something
        parameter_groups:
            none:
                sname: *sname
        product: test_product.txt

  
########### JUPYTER BOOK CONFIG ###########

##################################
# Jupyter Book Table of Contents #
##################################
book_toc:
    
  # See https://jupyterbook.org/en/stable/structure/configure.html for
  ## complete documentation of Jupyter book construction options

  format: jb-book

  # All filenames are notebook filename without the .ipynb, similar to above
  
  root: simple_no_params_nb  # root is the notebook that will be the homepage for the book
  parts:

    # Parts group notebooks into different sections in the Jupyter book
    ### table of contents, so you can organize different parts of your project.

    - caption: Notebook with parameters

      # Each chapter is the name of one of the notebooks that you executed
      ### in compute_notebooks above, also without .ipynb
      chapters:
        - file: params_nb
        - file: another_params_nb
    - caption: Notebook with parameter groups
      chapters:
          # Since we ran multiple_param_groups.ipynb with more than one
          ### group of parameters, multiple files were created--this 
          ### ensures all of them are included in the jupyter notebook
        - glob: multiple_param_groups_nb*


#####################################
# Keys for Jupyter Book _config.yml #
#####################################
book_config_keys:

  title: Example project   # Title of your jupyter book
  
  # Other keys can be added here, see https://jupyterbook.org/en/stable/customize/config.html
  ### for many more options

        
        
